### PR TITLE
timeout error.

### PR DESCRIPTION
**Pull request by blackknight75**

### CODE REVIEW

**Comment by blackknight75** [comment]
We are having an issues with a timeout error. It says that we are exceeding our request limit. We thought it was because we missed a done somewhere. Could you steer us in the right direction. @case-eee

**Comment by case-eee** [comment]
@blackknight75 i'm not sure what the issue is. i don't see anything just by reading through your code. my biggest question would be what does `FoodController.index(request, response)` actually do. i'm not seeing any committed code that corresponds with this. have you built this functionality yet?

**Comment by blackknight75** [comment]
@case-eee I think @cews7 figured it out. We didnt migrate our test data. At this point it appears to be working.

**Comment by case-eee** [comment]
ok cool @blackknight75 👍

**Pull request merged**
